name: pre_order_mobile_app
description: "EA Foods Pre-order Mobile App (Flutter + GetX + Clean Architecture + Offline-first)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # State Management & Routing
  get: ^4.6.6

  # Local Database (Offline-first)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # Firebase (optional if you want online sync later)
  cloud_firestore: ^5.5.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0

  # Utils
  intl: ^0.19.0
  equatable: ^2.0.5
  uuid: ^4.4.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.10

flutter:
  uses-material-design: true

  assets:
    - assets/
